import json
import sqlite3
import time

DB_PATH = '../corpus.db'
PROMPTS_FILE = '../securityeval_extended.json'
MODELS = ['gpt-4o', 'claude-sonnet', 'gemini-2.5-pro', 'deepseek-coder']

def mock_api_call(model, prompt, cwe):
    """Mocks a temperature=0 API response for local testing."""
    return f"// Generated by {model} for {cwe}\nvoid target_function() {{\n    // code\n}}"

def run_synthetic_generation():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    with open(PROMPTS_FILE, 'r') as f:
        prompts = json.load(f)
        
    total_generated = 0
    for p in prompts:
        prompt_id = p['ID']
        cwe_target = p['CWE']
        prompt_text = p['Prompt']
        
        for model in MODELS:
            # Plan requirement: temperature=0 (mocked here)
            generated_code = mock_api_call(model, prompt_text, cwe_target)
            
            cursor.execute('''
                INSERT INTO raw_files (source, model, prompt_id, cwe_target, content, language)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', ("SYNTHETIC", model, prompt_id, cwe_target, generated_code, "C"))
            total_generated += 1
            
    conn.commit()
    conn.close()
    print(f"Synthetic generation complete. Inserted {total_generated} programs into raw_files.")

if __name__ == "__main__":
    run_synthetic_generation()