import json
import sqlite3
import os

# Create an absolute base directory to dynamically find files
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DB_PATH = os.path.join(BASE_DIR, 'corpus.db')
PROMPTS_FILE = os.path.join(BASE_DIR, 'securityeval_extended.json')

MODELS = ['gpt-4o', 'claude-sonnet', 'gemini-2.5-pro', 'deepseek-coder']

def mock_api_call(model, prompt, cwe):
    """Mocks a temperature=0 API response for local testing with valid boilerplate (>150 bytes)."""
    return f"""// Generated by {model} for {cwe}
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 * Prompt: {prompt}
 * Target Security Evaluation Harness
 */
void target_function() {{
    char buffer[256];
    memset(buffer, 0, sizeof(buffer));
    printf("Executing synthetic harness for {cwe}\\n");
}}
"""

def run_synthetic_generation():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    with open(PROMPTS_FILE, 'r') as f:
        prompts = json.load(f)

    total_generated = 0
    for p in prompts:
        prompt_id = p.get('ID', f'PROMPT_{total_generated}')
        cwe_target = p.get('CWE', 'UNKNOWN')
        prompt_text = p.get('Prompt', '')

        for model in MODELS:
            # Plan requirement: temperature=0 (mocked here)
            generated_code = mock_api_call(model, prompt_text, cwe_target)

            # Map the synthetic data to the exact columns established by collect_github.py
            cursor.execute('''
                INSERT INTO raw_files (
                    repo_name, file_path, language, search_keyword, ai_tool, file_content, keyword_in_comment
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (
                "SYNTHETIC", 
                f"synthetic_{model}_{cwe_target}_{prompt_id}.c", 
                "C", 
                cwe_target, 
                model, 
                generated_code, 
                1 # Ensures it passes the Stage 1 filter
            ))
            
            total_generated += 1

    conn.commit()
    conn.close()
    print(f"Successfully generated and inserted {total_generated} synthetic C files into raw_files.")

if __name__ == "__main__":
    run_synthetic_generation()
